#!/usr/bin/env python
import ROOT
ROOT.gROOT.SetBatch(True)
ROOT.PyConfig.IgnoreCommandLineOptions = True
import sys
import os

import argparse
import commands


if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='Runs a NAF batch system for nanoAOD', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
	parser.add_argument('--infile', help='inputfile name',default=None, metavar='Dir')
	parser.add_argument('--outfile', help='inputfile name',default=None, metavar='site')
	args = parser.parse_args()
	
	TreeName="Events"
	file0 = ROOT.TFile.Open(args.infile)
	t = file0.Get(TreeName)	
	hcount = file0.Get("Count")
	hcountPos = file0.Get("CountPosWeight")
	hcountNeg = file0.Get("CountNegWeight")
	
	t.SetBranchStatus("*", 0)
	t.SetBranchStatus("event",1)
	t.SetBranchStatus("run",1)
	t.SetBranchStatus("luminosityBlock",1)
	t.SetBranchStatus("CaloMET_phi",1)
	t.SetBranchStatus("CaloMET_pt",1)
	t.SetBranchStatus("CaloMET_sumEt",1)
	t.SetBranchStatus("Flag_METFilters",1);
	t.SetBranchStatus("Jet_btagSF_cmva",1)
	t.SetBranchStatus("Jet_btagSF_cmva_up",1)
	t.SetBranchStatus("Jet_btagSF_cmva_down",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_jes",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_jes",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_lf",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_lf",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_hf",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_hf",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_hfstats1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_hfstats1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_hfstats2",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_hfstats2",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_lfstats1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_lfstats1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_lfstats2",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_lfstats2",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_cferr1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_cferr1",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_up_cferr2",1)
	t.SetBranchStatus("Jet_btagSF_cmva_shape_down_cferr2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_up",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_down",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_jes",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_jes",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_lf",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_lf",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_hf",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_hf",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_hfstats1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_hfstats1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_hfstats2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_hfstats2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_lfstats1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_lfstats1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_lfstats2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_lfstats2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_cferr1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_cferr1",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_up_cferr2",1)
	t.SetBranchStatus("Jet_btagSF_csvv2_shape_down_cferr2",1)
	t.SetBranchStatus("Jet_jecUncertTotal",1)
	t.SetBranchStatus("Jet_pt_nom",1)
	t.SetBranchStatus("Jet_mass_nom",1)
	t.SetBranchStatus("MET_pt_nom",1)
	t.SetBranchStatus("MET_phi_nom",1)
	t.SetBranchStatus("Jet_pt_jerUp",1)
	t.SetBranchStatus("Jet_mass_jerUp",1)
	t.SetBranchStatus("Jet_mass_jmrUp",1)
	t.SetBranchStatus("Jet_mass_jmsUp",1)
	t.SetBranchStatus("MET_pt_jerUp",1)
	t.SetBranchStatus("MET_phi_jerUp",1)
	t.SetBranchStatus("Jet_pt_jesTotalUp",1)
	t.SetBranchStatus("Jet_mass_jesTotalUp",1)
	t.SetBranchStatus("MET_pt_jesTotalUp",1)
	t.SetBranchStatus("MET_phi_jesTotalUp",1)
	t.SetBranchStatus("MET_pt_unclustEnUp",1)
	t.SetBranchStatus("MET_phi_unclustEnUp",1)
	t.SetBranchStatus("Jet_pt_jerDown",1)
	t.SetBranchStatus("Jet_mass_jerDown",1)
	t.SetBranchStatus("Jet_mass_jmrDown",1)
	t.SetBranchStatus("Jet_mass_jmsDown",1)
	t.SetBranchStatus("MET_pt_jerDown",1)
	t.SetBranchStatus("MET_phi_jerDown",1)
	t.SetBranchStatus("Jet_pt_jesTotalDown",1)
	t.SetBranchStatus("Jet_mass_jesTotalDown",1)
	t.SetBranchStatus("MET_pt_jesTotalDown",1)
	t.SetBranchStatus("MET_phi_jesTotalDown",1)
	t.SetBranchStatus("MET_pt_unclustEnDown",1)
	t.SetBranchStatus("MET_phi_unclustEnDown",1)
	t.SetBranchStatus("puWeight",1)
	t.SetBranchStatus("puWeightUp",1)
	t.SetBranchStatus("puWeightDown",1)
	t.SetBranchStatus("isData",1)
	t.SetBranchStatus("nLep",1)
	t.SetBranchStatus("nVeto",1)
	t.SetBranchStatus("nEl",1)
	t.SetBranchStatus("nMu",1)
	t.SetBranchStatus("nTightLeps",1)
	t.SetBranchStatus("nTightMu",1)
	t.SetBranchStatus("nTightEl",1)
	t.SetBranchStatus("tightLepsIdx",1)
	t.SetBranchStatus("Lep_pdgId",1)
	t.SetBranchStatus("Lep_pt",1)
	t.SetBranchStatus("Lep_eta",1)
	t.SetBranchStatus("Lep_phi",1)
	t.SetBranchStatus("Lep_Idx",1)
	t.SetBranchStatus("Lep_relIso",1)
	t.SetBranchStatus("Lep_miniIso",1)
	t.SetBranchStatus("Lep_hOverE",1)
	t.SetBranchStatus("Selected",1)
	t.SetBranchStatus("Lep2_pt",1)
	t.SetBranchStatus("Selected2",1)
	t.SetBranchStatus("LT",1)
	t.SetBranchStatus("ST",1)
	t.SetBranchStatus("MT",1)
	t.SetBranchStatus("DeltaPhiLepW",1)
	t.SetBranchStatus("dPhi",1)
	t.SetBranchStatus("Lp",1)
	t.SetBranchStatus("GendPhi",1)
	t.SetBranchStatus("GenLT",1)
	t.SetBranchStatus("GenMET",1)
	t.SetBranchStatus("ST1",1)
	t.SetBranchStatus("HT1",1)
	t.SetBranchStatus("HT",1)
	t.SetBranchStatus("nJets",1)
	t.SetBranchStatus("nBJet",1)
	t.SetBranchStatus("nBJetDeep",1)
	t.SetBranchStatus("nJets30",1)
	t.SetBranchStatus("Jets30Idx",1)
	t.SetBranchStatus("nBJets30",1)
	t.SetBranchStatus("nJets30Clean",1)
	t.SetBranchStatus("nJets40",1)
	t.SetBranchStatus("nBJets40",1)
	t.SetBranchStatus("htJet30j",1)
	t.SetBranchStatus("htJet30ja",1)
	t.SetBranchStatus("htJet40j",1)
	t.SetBranchStatus("Jet1_pt",1)
	t.SetBranchStatus("Jet2_pt",1)
	t.SetBranchStatus("Jet1_eta",1)
	t.SetBranchStatus("Jet2_eta",1)
	t.SetBranchStatus("nHighPtTopTag",1)
	t.SetBranchStatus("nHighPtTopTagPlusTau23",1)
	t.SetBranchStatus("LSLjetptGT80",1)
	t.SetBranchStatus("isSR",1)
	t.SetBranchStatus("Mll",1)
	t.SetBranchStatus("PD_JetHT",1)
	t.SetBranchStatus("PD_SingleEle",1)
	t.SetBranchStatus("PD_SingleMu",1)
	t.SetBranchStatus("PD_MET",1)
	t.SetBranchStatus("isDPhiSignal",1)
	t.SetBranchStatus("RA2_muJetFilter",1)
	t.SetBranchStatus("Flag_fastSimCorridorJetCleaning",1)
	t.SetBranchStatus("minMWjj",1)
	t.SetBranchStatus("minMWjjPt",1)
	t.SetBranchStatus("bestMWjj",1)
	t.SetBranchStatus("bestMWjjPt",1)
	t.SetBranchStatus("bestMTopHad",1)
	t.SetBranchStatus("bestMTopHadPt",1)
	t.SetBranchStatus("iso_had",1)
	t.SetBranchStatus("iso_pt",1)
	t.SetBranchStatus("iso_MT2",1)
	t.SetBranchStatus("iso_Veto",1)
	t.SetBranchStatus("nLepGood",1)
	t.SetBranchStatus("nLepOther",1)
	t.SetBranchStatus("LepGood_Cutbased",1)
	t.SetBranchStatus("LepOther_Cutbased",1)
	t.SetBranchStatus("Xsec",1)
	t.SetBranchStatus("Muon_effSF",1)
	t.SetBranchStatus("Electron_effSF",1)
	t.SetBranchStatus("lepSF",1)
	t.SetBranchStatus("TightEl_eCorr",1)
	t.SetBranchStatus("Met",1)
	t.SetBranchStatus("minDPhiBMET",1)
	t.SetBranchStatus("minDPhiJMET",1)
	t.SetBranchStatus("idxMinDPhiBMET",1)
	t.SetBranchStatus("mTClBPlusMET",1)
	t.SetBranchStatus("mTBJetMET",1)
	t.SetBranchStatus("mTLepMET",1)
	t.SetBranchStatus("mLepBJet",1)
	t.SetBranchStatus("nCentralJet30",1)
	t.SetBranchStatus("LepBMass",1)
	t.SetBranchStatus("MTbnu",1)
	t.SetBranchStatus("Mtop",1)
	t.SetBranchStatus("MTtop",1)
	t.SetBranchStatus("METovTop",1)
	t.SetBranchStatus("METTopPhi",1)
	t.SetBranchStatus("MtopDecor",1)
	t.SetBranchStatus("TopPt",1)
	t.SetBranchStatus("TopEt",1)
	t.SetBranchStatus("nBMinVariantsTopVars",1)
	t.SetBranchStatus("TopVarsMTbnuMin",1)
	t.SetBranchStatus("TopVarsLepBMassMin",1)
	t.SetBranchStatus("TopVarsMTtopMin",1)
	t.SetBranchStatus("TopVarsMtopMin",1)
	t.SetBranchStatus("TopVarsMETovTopMin",1)
	t.SetBranchStatus("TopVarsMtopDecorMin",1)
	t.SetBranchStatus("TopVarsTopPtMin",1)
	t.SetBranchStatus("TopVarsTopEtMin",1)
	t.SetBranchStatus("MTW",1)
	t.SetBranchStatus("MW1",1)
	t.SetBranchStatus("MW2",1)
	t.SetBranchStatus("minDphiLepB",1)
	t.SetBranchStatus("minDphiLepBidx",1)
	t.SetBranchStatus("GenTopPt",1)
	t.SetBranchStatus("GenAntiTopPt",1)
	t.SetBranchStatus("TopPtWeight",1)
	t.SetBranchStatus("TopPtWeightII",1)
	t.SetBranchStatus("GenTTBarPt",1)
	t.SetBranchStatus("GenTTBarWeight",1)
	t.SetBranchStatus("ISRTTBarWeight",1)
	t.SetBranchStatus("GenGGPt",1)
	t.SetBranchStatus("ISRSigUp",1)
	t.SetBranchStatus("ISRSigDown",1)
	t.SetBranchStatus("DilepNJetCorr",1)
	t.SetBranchStatus("DilepNJetWeightConstUp",1)
	t.SetBranchStatus("DilepNJetWeightSlopeUp",1)
	t.SetBranchStatus("DilepNJetWeightConstDn",1)
	t.SetBranchStatus("DilepNJetWeightSlopeDn",1)
	t.SetBranchStatus("WpolWup",1)
	t.SetBranchStatus("WpolWdown",1)
	t.SetBranchStatus("passFilters",1)
	t.SetBranchStatus("passFiltersMoriond2017Tight",1)
	t.SetBranchStatus("passCSCFilterList",1)
	t.SetBranchStatus("HLT_EleOR",1)
	t.SetBranchStatus("HLT_MuOR",1)
	t.SetBranchStatus("HLT_LepOR",1)
	t.SetBranchStatus("HLT_MetOR",1)
	t.SetBranchStatus("HLT_Ele115_CaloIdVT_GsfTrkIdT",1)
	t.SetBranchStatus("HLT_Ele15_IsoVVVL_PFHT450",1)
	t.SetBranchStatus("HLT_Mu50",1)
	t.SetBranchStatus("HLT_Mu15_IsoVVVL_PFHT450 ",1)
	t.SetBranchStatus("HLT_PFJet450",1)
	t.SetBranchStatus("HLT_IsoMu24",1)
	t.SetBranchStatus("HLT_HT350MET100",1)
	t.SetBranchStatus("HLT_Ele15_IsoVVVL_PFHT350_PFMET50",1)
	t.SetBranchStatus("HLT_Ele105_CaloIdVT_GsfTrkIdT",1)
	t.SetBranchStatus("HLT_MuHT350MET50",1)
	t.SetBranchStatus("HLT_Ele27_WPTight_Gsf",1)
	t.SetBranchStatus("HLT_Ele50_CaloIdVT_GsfTrkIdT_PFJet165",1)
	t.SetBranchStatus("HLT_Ele15_IsoVVVL_PFHT350",1)
	t.SetBranchStatus("HLT_Ele15_IsoVVVL_PFHT400",1)
	t.SetBranchStatus("HLT_Mu15_IsoVVVL_PFHT400",1)
	t.SetBranchStatus("HLT_Mu15_IsoVVVL_PFHT350",1)
	t.SetBranchStatus("TrigEff",1)
	t.SetBranchStatus("GenDeltaPhiLepWSum",1)
	t.SetBranchStatus("GenDeltaPhiLepWDirect",1)
	t.SetBranchStatus("GenWSumMass",1)
	t.SetBranchStatus("GenWDirectMass",1)
	t.SetBranchStatus("nidxGenWs",1)
	t.SetBranchStatus("GenmTLepNu",1)
	t.SetBranchStatus("LeptonDecayChannelFlag",1)
	t.SetBranchStatus("nIsr",1)
	t.SetBranchStatus("nISRweight",1)
	t.SetBranchStatus("nISRttweightsyst_up",1)
	t.SetBranchStatus("nISRttweightsyst_down",1)
	t.SetBranchStatus("Flag_METFilters",1);
	t.SetBranchStatus("LHE_HTIncoming",1)
	t.SetBranchStatus("Pileup_nTrueInt",1);
	t.SetBranchStatus("mGo",1);
	t.SetBranchStatus("mLSP",1);
	t.SetBranchStatus("susyXsec",1);
	t.SetBranchStatus("susyNgen",1);
	t.SetBranchStatus("totalNgen",1);
	t.SetBranchStatus("susyWgen",1);
	t.SetBranchStatus("nISRweightsyst_up",1);
	t.SetBranchStatus("nISRweightsyst_down",1);
	t.SetBranchStatus("genTau_grandmotherId",1);
	t.SetBranchStatus("genTau_motherId",1);
	t.SetBranchStatus("genLep_grandmotherId",1);
	t.SetBranchStatus("genLep_motherId",1);
	t.SetBranchStatus("genWeight",1);
	
	outname = args.outfile
	fout = ROOT.TFile(outname, 'RECREATE' )
	fout.cd()
	outTree = t.CloneTree(0)
	for i in range(t.GetEntries()):
		t.GetEntry(i)
		if t.HT >= 350 and t.LT >= 150 :
			outTree.Fill()
	outTree.AutoSave()
	if file0.GetListOfKeys().Contains("Count"):
		hcount.Write()
		hcountPos.Write()
		hcountNeg.Write()
	fout.Write()
	fout.Close()
	
